-- Starter measures for the imported fact_group6_usage_daily table.
-- Create these in Power BI Desktop or through pbi-cli after connecting to a model.

Usage Events = SUM(fact_group6_usage_daily[EVENT_COUNT])

Active Accounts = DISTINCTCOUNT(dim_group6_account_service[ACCOUNT_ID])

Prompt Count = SUM(fact_group6_usage_daily[PROMPTS])

Input Token Count = SUM(fact_group6_usage_daily[INPUT_TOKENS])

Output Token Count = SUM(fact_group6_usage_daily[OUTPUT_TOKENS])

Total Token Count = SUM(fact_group6_usage_daily[TOTAL_TOKENS])

Token Block Count = SUM(fact_group6_usage_daily[TOKEN_BLOCKS])

Usage Revenue USD = SUM(fact_group6_usage_daily[USAGE_REVENUE])

Revenue per 1K Tokens = DIVIDE([Usage Revenue USD], [Token Block Count])

Average Tokens per Event = DIVIDE([Total Token Count], [Usage Events])

Unmapped GL Revenue USD =
CALCULATE([Usage Revenue USD], FILTER(fact_group6_usage_daily, VALUE(fact_group6_usage_daily[GL_ID]) = 0))

Unmapped GL Usage Events =
CALCULATE([Usage Events], FILTER(fact_group6_usage_daily, VALUE(fact_group6_usage_daily[GL_ID]) = 0))

Unmapped GL Token Count =
CALCULATE([Total Token Count], FILTER(fact_group6_usage_daily, VALUE(fact_group6_usage_daily[GL_ID]) = 0))

Billed USD = SUM(fact_group6_finance_monthly[BILLED_USD])

Unbilled USD = SUM(fact_group6_finance_monthly[UNBILLED_USD])

Collected USD = SUM(fact_group6_finance_monthly[COLLECTED_USD])

Outstanding USD = SUM(fact_group6_finance_monthly[OUTSTANDING_USD])

Billed Bill Count = SUM(fact_group6_finance_monthly[BILLED_BILL_COUNT])

Unbilled Bill Count = SUM(fact_group6_finance_monthly[UNBILLED_BILL_COUNT])

AIT Taxable Base USD = SUM(fact_group6_finance_monthly[AIT_TAXABLE_BASE_USD])

AIT Collected USD = SUM(fact_group6_finance_monthly[AIT_COLLECTED_USD])

Expected AIT USD = SUM(fact_group6_finance_monthly[EXPECTED_AIT_USD])

AIT Gap USD = SUM(fact_group6_finance_monthly[AIT_GAP_USD])

Customer Bill Count = COUNTROWS(fact_group6_customer_bills)

Paid Bill Count = CALCULATE([Customer Bill Count], fact_group6_customer_bills[BILL_STATUS] = "Paid")

Unpaid Bill Count = CALCULATE([Customer Bill Count], fact_group6_customer_bills[BILL_STATUS] = "Unpaid")

Unbilled Customer Bill Count = CALCULATE([Customer Bill Count], fact_group6_customer_bills[BILL_STATUS] = "Unbilled")

Customer Bills Billed USD = SUM(fact_group6_customer_bills[BILLED_USD])

Customer Bills Received USD = SUM(fact_group6_customer_bills[RECEIVED_USD])

Customer Bills Outstanding USD = SUM(fact_group6_customer_bills[OUTSTANDING_USD])
